# Generated by Django 5.0.6 on 2024-06-06 18:42

import django.db.models.deletion
import parser.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('url', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('filename', models.CharField(default=None, max_length=1000)),
                ('source_shop', models.CharField(max_length=255, null=True)),
                ('image_type', models.CharField(choices=[('product_image', 'product_image'), ('manufacturer_image', 'manufacturer_image'), ('other_image', 'other_image')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('source_url', models.CharField(max_length=2550, primary_key=True, serialize=False)),
                ('source_shop', models.CharField(max_length=255)),
                ('name', models.CharField(default=None, max_length=255, null=True)),
                ('path', models.CharField(default=None, max_length=1024, null=True)),
                ('has_products', models.BooleanField(blank=True, default=True)),
                ('child_urls', models.TextField(default=None, null=True)),
                ('product_urls', models.JSONField(default=None, null=True)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='parser.category')),
            ],
        ),
        migrations.CreateModel(
            name='GrabSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parser_name', models.CharField(max_length=100)),
                ('parser_mode', models.CharField(choices=[('CATEGORY_URLS', parser.models.Modes['CATEGORY_URLS']), ('PRODUCT_URLS', parser.models.Modes['PRODUCT_URLS']), ('KEYWORDS', parser.models.Modes['KEYWORDS']), ('ALL_PRODUCTS', parser.models.Modes['ALL_PRODUCTS'])], max_length=100)),
                ('max_page_amount', models.IntegerField(default=2, verbose_name='Max category pages')),
                ('min_price', models.IntegerField(default=200)),
                ('max_price', models.IntegerField(default=700)),
                ('category_urls', models.TextField(blank=True, verbose_name='Category URLs')),
                ('product_urls', models.TextField(blank=True, default='https://www.fahrrad-xxl.de/carver-drift-e-510-m000009360', verbose_name='Product URLs')),
                ('keywords', models.TextField(blank=True, max_length=1000, verbose_name='Keywords')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GrabStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'active'), ('pending', 'pending'), ('running', 'running'), ('error', 'error'), ('terminated', 'terminated'), ('finished', 'finished')], max_length=100)),
                ('settings_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.grabsettings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('source_url', models.CharField(blank=True, max_length=2550, primary_key=True, serialize=False, unique=True)),
                ('source_shop', models.CharField(max_length=255, null=True)),
                ('product_type', models.CharField(choices=[('single', 'single'), ('parent', 'parent'), ('child', 'child')], default='single', max_length=10)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('sku', models.CharField(default=None, max_length=255, null=True)),
                ('product_number', models.CharField(blank=True, max_length=255)),
                ('ean', models.CharField(blank=True, max_length=255)),
                ('manufacturer_number', models.CharField(blank=True, max_length=255)),
                ('manufacturer_name', models.CharField(blank=True, max_length=255)),
                ('strike_price', models.FloatField(default=0, max_length=100)),
                ('price', models.FloatField(default=0, max_length=100)),
                ('short_description', models.TextField(default=None, null=True)),
                ('html_description', models.TextField(default=None, null=True)),
                ('details_description', models.TextField(default=None, null=True)),
                ('energy_class', models.CharField(default=None, max_length=1000, null=True)),
                ('energy_icon_url', models.CharField(default=None, max_length=1000, null=True)),
                ('energy_icon_filename', models.CharField(default=None, max_length=1000, null=True)),
                ('energy_icon_ext', models.CharField(default=None, max_length=1000, null=True)),
                ('energy_label_url', models.CharField(default=None, max_length=1000, null=True)),
                ('energy_label_filename', models.CharField(default=None, max_length=1000, null=True)),
                ('energy_label_ext', models.CharField(default=None, max_length=1000, null=True)),
                ('energy_pdf_url', models.CharField(default=None, max_length=1000, null=True)),
                ('energy_pdf_filename', models.CharField(default=None, max_length=1000, null=True)),
                ('energy_pdf_ext', models.CharField(default=None, max_length=1000, null=True)),
                ('purchase_unit', models.FloatField(default=0)),
                ('reference_unit', models.IntegerField(default=0)),
                ('pack_unit', models.CharField(default='ST', max_length=255)),
                ('pack_unit_plural', models.CharField(default='ST', max_length=255)),
                ('unit', models.CharField(blank=True, max_length=255, null=None)),
                ('shipping_tags', models.JSONField(default=list)),
                ('currency', models.CharField(default='EUR', max_length=5)),
                ('weight', models.FloatField(default=None, null=True)),
                ('lenght', models.FloatField(default=None, null=True)),
                ('height', models.FloatField(default=None, null=True)),
                ('width', models.FloatField(default=None, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='parser.category')),
                ('images', models.ManyToManyField(blank=True, related_name='image_of', to='parser.image')),
                ('main_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_image_of', to='parser.image')),
                ('manufacturer_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parser.image')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='parser.product')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='for_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='of_product', to='parser.product'),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('content', models.TextField(max_length=5000)),
                ('points', models.IntegerField()),
                ('time', models.DateField()),
                ('for_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='parser.product')),
            ],
        ),
    ]
