# Generated by Django 5.0.6 on 2024-06-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_alter_product_ean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturer_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
