# Generated by Django 5.0.6 on 2024-06-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_alter_product_manufacturer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='html_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(null=True),
        ),
    ]
