# Generated by Django 5.0.6 on 2024-06-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0005_alter_product_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
