# Generated by Django 5.0.6 on 2024-06-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0010_alter_productreview_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manufacturer_image',
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_image',
            field=models.ManyToManyField(null=True, to='parser.image'),
        ),
    ]
