# Generated by Django 5.0.6 on 2024-06-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0012_remove_image_for_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='product_reviews', to='parser.productreview'),
        ),
    ]
