# Generated by Django 5.0.6 on 2024-06-09 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0014_remove_product_reviews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manufacturer_image',
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parser.image'),
        ),
    ]
