# Generated by Django 5.0.6 on 2024-06-10 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0015_remove_product_manufacturer_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopwareShop',
            fields=[
                ('domain', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('valid', models.BooleanField(default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopwareAccessToken',
            fields=[
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='parser.shopwareshop')),
                ('token', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
                ('valid_until', models.DateTimeField()),
            ],
        ),
    ]
