# Generated by Django 5.0.6 on 2024-06-18 20:26

import django.db.models.deletion
import parser.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0016_shopwareshop_shopwareaccesstoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopwareaccesstoken',
            name='token',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='shopwareshop',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parser_name', models.CharField(max_length=100)),
                ('parser_mode', models.CharField(choices=[('CATEGORY_URLS', parser.models.Modes['CATEGORY_URLS']), ('PRODUCT_URLS', parser.models.Modes['PRODUCT_URLS']), ('KEYWORDS', parser.models.Modes['KEYWORDS']), ('ALL_PRODUCTS', parser.models.Modes['ALL_PRODUCTS'])], default=parser.models.Modes['PRODUCT_URLS'], max_length=100)),
                ('max_page_amount', models.IntegerField(default=2, verbose_name='Max category pages')),
                ('min_price', models.IntegerField(default=200)),
                ('max_price', models.IntegerField(default=700)),
                ('category_urls', models.TextField(blank=True, verbose_name='Category URLs')),
                ('product_urls', models.TextField(blank=True, default='https://www.fahrrad-xxl.de/carver-drift-e-510-m000009360', verbose_name='Product URLs')),
                ('keywords', models.TextField(blank=True, max_length=1000, verbose_name='Keywords')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='grabstatus',
            name='settings_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.settings'),
        ),
        migrations.DeleteModel(
            name='GrabSettings',
        ),
    ]
