# Generated by Django 5.0.6 on 2024-06-18 20:33

import parser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0017_alter_shopwareaccesstoken_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='destination',
            field=models.CharField(choices=[('CATEGORY_URLS', parser.models.Modes['CATEGORY_URLS']), ('PRODUCT_URLS', parser.models.Modes['PRODUCT_URLS']), ('KEYWORDS', parser.models.Modes['KEYWORDS']), ('ALL_PRODUCTS', parser.models.Modes['ALL_PRODUCTS'])], default='Shopware 6', max_length=100),
        ),
    ]
