# Generated by Django 5.0.6 on 2024-06-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0018_settings_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uploaded_to_shops',
            field=models.ManyToManyField(blank=True, related_name='uploaded_products', to='parser.shopwareshop'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='destination',
            field=models.CharField(blank=True, choices=[('Shopware 6', 'Shopware 6'), ('WooCommerce', 'WooCommerce'), ('Shopify', 'Shopify')], default='Shopware 6', max_length=100),
        ),
    ]
