# Generated by Django 5.0.6 on 2024-06-20 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0019_product_uploaded_to_shops_alter_settings_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='target_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings', to='parser.shopwareshop'),
        ),
    ]
