# Generated by Django 5.0.6 on 2024-06-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0020_settings_target_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_path',
            field=models.JSONField(default=None, null=True),
        ),
    ]
