# Generated by Django 5.0.6 on 2024-06-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0021_product_category_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopwareaccesstoken',
            name='valid_until',
            field=models.DateTimeField(blank=True),
        ),
    ]
