# Generated by Django 5.0.6 on 2024-06-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0022_alter_shopwareaccesstoken_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopwareaccesstoken',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
