# Generated by Django 5.0.6 on 2024-06-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0023_alter_shopwareaccesstoken_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='properties',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer_number',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='options',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
