# Generated by Django 5.0.6 on 2024-06-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0024_product_properties_alter_product_manufacturer_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='uploaded_to_shops',
            field=models.ManyToManyField(blank=True, related_name='uploaded_images', to='parser.shopwareshop'),
        ),
    ]
