# Generated by Django 5.0.6 on 2024-06-24 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0026_alter_product_manufacturer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopwareaccesstoken',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='parser.shopwareshop'),
        ),
    ]
